# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: akka-user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Akka
    ports:
      - 5432:5432 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080