version: '3'

services:
  lighthouse:
    image: petabridge/lighthouse:v0.9.2
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "webcrawler"
      CLUSTER_IP: lighthouse
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"


  webcrawler.web:
    image: webcrawler.web
    build:
      context: .
      dockerfile: src/WebCrawler.Web/Dockerfile
    ports:
      - '8080:80'
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.web
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"

  webcrawler.crawlservice:
    image: webcrawler.crawlservice
    build:
      context: .
      dockerfile: src/WebCrawler.CrawlService/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.crawlservice
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"

  webcrawler.trackerservice:
    image: webcrawler.trackerservice
    build:
      context: .
      dockerfile: src/WebCrawler.TrackerService/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.trackerservice
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"
