version: '3'

services:
  lighthouse:
    image: petabridge/lighthouse:0.9.1
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "webcrawler"
      CLUSTER_IP: lighthouse
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"


  webcrawler.web:
    image: webcrawler.web
    build:
      context: .
      dockerfile: src/WebCrawler.Web/Dockerfile
    ports:
      - '80:80'
      - '16666:16666'
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.web
      CLUSTER_PORT: 16666

  webcrawler.crawlservice:
    image: webcrawler.crawlservice
    build:
      context: .
      dockerfile: src/WebCrawler.CrawlService/Dockerfile
    ports:
      - '5213:5213'
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.crawlservice
      CLUSTER_PORT: 5213

  webcrawler.trackerservice:
    image: webcrawler.trackerservice
    build:
      context: .
      dockerfile: src/WebCrawler.TrackerService/Dockerfile
    ports:
      - '5212:5212'
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: webcrawler.trackerservice
      CLUSTER_PORT: 5212
