name: pr_validation

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: ${{ matrix.solution-name }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        solution-name:
          - ShardingSqlServer
          - ClusterClient
          - Aspire
          - CqrsSqlServer
          - AutofacIntegration
          - ReliableRabbitMQ
          - SqlInitContainer
          - LongRunningTasks
        include:
          - solution-name: ShardingSqlServer
            solution-path: src/clustering/sharding-sqlserver/ShardingSqlServer.slnx
          - solution-name: ClusterClient
            solution-path: src/clustering/cluster-client/ClusterClientSample.slnx
          - solution-name: Aspire
            solution-path: src/clustering/cluster-bootstrap/Aspire/Aspire.slnx
          - solution-name: CqrsSqlServer
            solution-path: src/cqrs/cqrs-sqlserver/CqrsSqlServer.slnx
          - solution-name: AutofacIntegration
            solution-path: src/dependency-injection/AutofacIntegration/AutofacIntegration.slnx
          - solution-name: ReliableRabbitMQ
            solution-path: src/reliability/rabbitmq-backpressure/ReliableRabbitMQ.slnx
          - solution-name: SqlInitContainer
            solution-path: infrastructure/mssql-init-container/src/Akka.SqlInitContainer.slnx
          - solution-name: LongRunningTasks
            solution-path: src/async/long-running-tasks/LongRunningTasks.slnx
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: "./global.json"

      - name: "Update release notes"
        shell: pwsh
        run: ./build.ps1

      - name: "dotnet build"
        run: dotnet build ${{ matrix.solution-path }} -c Release

      - name: "dotnet test"
        run: dotnet test ${{ matrix.solution-path }} -c Release --no-build
